image:
  file: .gitpod.Dockerfile

checkoutLocation: dazzle
workspaceLocation: dazzle
tasks:
  - init:  |
      touch /tmp/.init-lock
      go get -v ./...
      wget -c https://github.com/moby/buildkit/releases/download/v0.8.3/buildkit-v0.8.3.linux-amd64.tar.gz  -O - | tar -xz -C /workspace/
      rm /tmp/.init-lock
    name: buildkitd
    command: sudo /workspace/bin/buildkitd
  - init: sleep 1 && while [ -f /tmp/.init-lock ]; do sleep 1; done
    openMode: tab-after
    command: docker run --rm -d -p 5000:5000 --name registry registry:2
vscode:
  extensions:
    - golang.go