builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/32leaves/dazzle/cmd.version={{.Version}}-{{.ShortCommit}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    binaries:
    - dazzle
    dockerfile: Dockerfile
    image_templates:
    - "csweichel/dazzle:{{ .Tag }}"
    - "csweichel/dazzle:v{{ .Major }}"
    - "csweichel/dazzle:v{{ .Major }}.{{ .Minor }}"
    - "csweichel/dazzle:latest"
    extra_files:
    - README.md
